version: "3.8"

services:

  mysqldb:
    image: mysql:8.0
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: EntreBicisDataB
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql
    command: --bind-address=0.0.0.0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: entrebicis-backend:latest
    build: .
    restart: no
    depends_on:
      mysqldb:
        condition: service_healthy
    ports:
      - "8443:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/EntreBicisDataB?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    volumes:
      - ./backend/logs:/app/logs

volumes:
  db: